apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'multi-server-deployment'
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
        containers:
        - name: multi-server
          image: raghav141988/multi-server:v1
          ports:
            - containerPort: 5000
          env:         
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                    name: pgpassword
                    key:  PGPASSWORD
            