apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'multi-worker-deployment'
  
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: multi-worker
  template:
    metadata:
      labels:
        component: multi-worker
        
    spec:
        containers:
        - name: 'multi-worker'
          image: 'raghav141988/multi-worker:v1'
          env:         
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
        